# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'Bangumi M' do
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
    pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git', :branch => 'swift3'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'swift3'
    # pod 'TagWriteView'
    pod 'MJRefresh'
    pod 'Cosmos', '~> 3.0'
    pod 'Kanna', :git => 'https://github.com/tid-kijyun/Kanna', :branch => 'swift3.0'
    # pod 'ReachabilitySwift'
    pod 'UITextField+Shake', '~> 1.1'
    pod 'SVProgressHUD'
    pod 'Canvas'
    pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-3.0'

    abstract_target 'tests' do
        target 'Bangumi M Tests'
        
        inherit! :search_paths
        pod 'OHHTTPStubs'
    end
end
