# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!
pod 'HanekeSwift'
pod 'TagWriteView'
pod 'MJRefresh'
pod 'Cosmos', :git => 'https://github.com/exchangegroup/Cosmos.git', :branch => 'swift-1'