# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

target 'Bangumi M' do
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireImage', '~> 3.3'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'Cosmos', '~> 11.0'
    pod 'Kanna', '~> 2.1.0'
    pod 'UITextField+Shake', '~> 1.1'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git', :commit => 'ba369a1'
    pod 'Canvas', '~> 0.1.2'
    pod 'KeychainAccess', '~> 3.0.2'
    pod 'IGListKit', '~> 3.0'

    # pod 'ReachabilitySwift'
    # pod 'TagWriteView'
    pod 'MGSwipeTableCell'
    pod 'EUMTouchPointView'
    pod 'PPCopiableLabel'

    target 'Bangumi M Tests' do
        inherit! :search_paths
        pod 'OHHTTPStubs'
    end

    target 'Bangumi M UITests' do
        inherit! :search_paths
        pod 'SimulatorStatusMagic'
    end
end
